// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3lAUWyFlG084Z1mRrM4LOMvBDvEJ97I',
    appId: '1:1054330765036:web:fa42319ae06c974e496fc9',
    messagingSenderId: '1054330765036',
    projectId: 'mambolimpo-2eedd',
    authDomain: 'mambolimpo-2eedd.firebaseapp.com',
    storageBucket: 'mambolimpo-2eedd.firebasestorage.app',
    measurementId: 'G-CXD0FVZK5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlUhPM0NjnTOIgqxvYi7ncgc1-ZNtzOq0',
    appId: '1:1054330765036:android:d4ffe10d99895e86496fc9',
    messagingSenderId: '1054330765036',
    projectId: 'mambolimpo-2eedd',
    storageBucket: 'mambolimpo-2eedd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ZNCRx3HohQmAWxnu-qGp85h86INqATI',
    appId: '1:1054330765036:ios:9f2fc2cf3a15092e496fc9',
    messagingSenderId: '1054330765036',
    projectId: 'mambolimpo-2eedd',
    storageBucket: 'mambolimpo-2eedd.firebasestorage.app',
    iosClientId: '1054330765036-qtum00rkgs1mf66ee2keug9s98jcde6q.apps.googleusercontent.com',
    iosBundleId: 'com.ataryjr.mambolimpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ZNCRx3HohQmAWxnu-qGp85h86INqATI',
    appId: '1:1054330765036:ios:9f2fc2cf3a15092e496fc9',
    messagingSenderId: '1054330765036',
    projectId: 'mambolimpo-2eedd',
    storageBucket: 'mambolimpo-2eedd.firebasestorage.app',
    iosClientId: '1054330765036-qtum00rkgs1mf66ee2keug9s98jcde6q.apps.googleusercontent.com',
    iosBundleId: 'com.ataryjr.mambolimpo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_3lAUWyFlG084Z1mRrM4LOMvBDvEJ97I',
    appId: '1:1054330765036:web:896e3939e084730b496fc9',
    messagingSenderId: '1054330765036',
    projectId: 'mambolimpo-2eedd',
    authDomain: 'mambolimpo-2eedd.firebaseapp.com',
    storageBucket: 'mambolimpo-2eedd.firebasestorage.app',
    measurementId: 'G-GZ77KDJBGC',
  );
}
